/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(general)': RouteRecordInfo<'/(general)', '/', Record<never, never>, Record<never, never>, '/(general)/' | '/(general)/about' | '/(general)/auth/google/callback'>,
    '/(general)/': RouteRecordInfo<'/(general)/', '/', Record<never, never>, Record<never, never>>,
    '/(general)/about': RouteRecordInfo<'/(general)/about', '/about', Record<never, never>, Record<never, never>>,
    '/(general)/auth/google/callback': RouteRecordInfo<'/(general)/auth/google/callback', '/auth/google/callback', Record<never, never>, Record<never, never>>,
    '/(header)': RouteRecordInfo<'/(header)', '/', Record<never, never>, Record<never, never>, '/(header)/collections' | '/(header)/play' | '/(header)/recipes/' | '/(header)/recipes/[recipeId]'>,
    '/(header)/collections': RouteRecordInfo<'/(header)/collections', '/collections', Record<never, never>, Record<never, never>>,
    '/(header)/play': RouteRecordInfo<'/(header)/play', '/play', Record<never, never>, Record<never, never>>,
    '/(header)/recipes/': RouteRecordInfo<'/(header)/recipes/', '/recipes', Record<never, never>, Record<never, never>>,
    '/(header)/recipes/[recipeId]': RouteRecordInfo<'/(header)/recipes/[recipeId]', '/recipes/:recipeId', { recipeId: ParamValue<true> }, { recipeId: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(general).vue': {
      routes: '/(general)' | '/(general)/' | '/(general)/about' | '/(general)/auth' | '/(general)/auth/google/callback' | '/(general)/auth/google'
      views: 'default'
    }
    'src/pages/(general)/index.vue': {
      routes: '/(general)/'
      views: never
    }
    'src/pages/(general)/about.vue': {
      routes: '/(general)/about'
      views: never
    }
    'src/pages/(general)/auth/google/callback.vue': {
      routes: '/(general)/auth/google/callback'
      views: never
    }
    'src/pages/(header).vue': {
      routes: '/(header)' | '/(header)/recipes/' | '/(header)/recipes/[recipeId]' | '/(header)/collections' | '/(header)/play' | '/(header)/recipes'
      views: 'default'
    }
    'src/pages/(header)/collections.vue': {
      routes: '/(header)/collections'
      views: never
    }
    'src/pages/(header)/play.vue': {
      routes: '/(header)/play'
      views: never
    }
    'src/pages/(header)/recipes/index.vue': {
      routes: '/(header)/recipes/'
      views: never
    }
    'src/pages/(header)/recipes/[recipeId].vue': {
      routes: '/(header)/recipes/[recipeId]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
