/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(general)': RouteRecordInfo<'/(general)', '/', Record<never, never>, Record<never, never>, '/(general)/'>,
    '/(general)/': RouteRecordInfo<'/(general)/', '/', Record<never, never>, Record<never, never>>,
    '/(header)': RouteRecordInfo<'/(header)', '/', Record<never, never>, Record<never, never>, '/(header)/about' | '/(header)/collections/' | '/(header)/collections/[recipeId]' | '/(header)/play' | '/(header)/profile' | '/(header)/recipes/' | '/(header)/recipes/[recipeId]'>,
    '/(header)/about': RouteRecordInfo<'/(header)/about', '/about', Record<never, never>, Record<never, never>>,
    '/(header)/collections/': RouteRecordInfo<'/(header)/collections/', '/collections', Record<never, never>, Record<never, never>>,
    '/(header)/collections/[recipeId]': RouteRecordInfo<'/(header)/collections/[recipeId]', '/collections/:recipeId', { recipeId: ParamValue<true> }, { recipeId: ParamValue<false> }>,
    '/(header)/play': RouteRecordInfo<'/(header)/play', '/play', Record<never, never>, Record<never, never>>,
    '/(header)/profile': RouteRecordInfo<'/(header)/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/(header)/recipes/': RouteRecordInfo<'/(header)/recipes/', '/recipes', Record<never, never>, Record<never, never>>,
    '/(header)/recipes/[recipeId]': RouteRecordInfo<'/(header)/recipes/[recipeId]', '/recipes/:recipeId', { recipeId: ParamValue<true> }, { recipeId: ParamValue<false> }>,
    '/auth/google/callback': RouteRecordInfo<'/auth/google/callback', '/auth/google/callback', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(general).vue': {
      routes: '/(general)' | '/(general)/'
      views: 'default'
    }
    'src/pages/(general)/index.vue': {
      routes: '/(general)/'
      views: never
    }
    'src/pages/(header).vue': {
      routes: '/(header)' | '/(header)/recipes/' | '/(header)/collections/' | '/(header)/recipes/[recipeId]' | '/(header)/collections/[recipeId]' | '/(header)/about' | '/(header)/colections' | '/(header)/collections' | '/(header)/play' | '/(header)/profile' | '/(header)/recipes'
      views: 'default'
    }
    'src/pages/(header)/about.vue': {
      routes: '/(header)/about'
      views: never
    }
    'src/pages/(header)/collections/index.vue': {
      routes: '/(header)/collections/'
      views: never
    }
    'src/pages/(header)/collections/[recipeId].vue': {
      routes: '/(header)/collections/[recipeId]'
      views: never
    }
    'src/pages/(header)/play.vue': {
      routes: '/(header)/play'
      views: never
    }
    'src/pages/(header)/profile.vue': {
      routes: '/(header)/profile'
      views: never
    }
    'src/pages/(header)/recipes/index.vue': {
      routes: '/(header)/recipes/'
      views: never
    }
    'src/pages/(header)/recipes/[recipeId].vue': {
      routes: '/(header)/recipes/[recipeId]'
      views: never
    }
    'src/pages/auth/google/callback.vue': {
      routes: '/auth/google/callback'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
